ktor:
  deployment:
    port: 8080
  application:
    modules:
      - moe._47saikyo.ApplicationKt.modules

exposed:
  datasource:
    driverClassName: "org.mariadb.jdbc.Driver"
    jdbcUrl: "jdbc:mariadb://localhost:3306/drm-backend?characterEncoding=utf-8&serverTimezone=Asia/Shanghai"
    username: "root"
    password: "123456"

JWT:
  subject: "Digital Right Manager Access License"
  issuer: "Digital Right Manager"
  audience: "Browser Application"
  secret: "secret"

chain:
  socket: "http://192.168.10.108:8545"
  address: "0xcb7f6d5c8f5c71c3f604f6fec874a97007dfe4fe"
  password: "test"
  walletFile: "/KeyStore/UTC--2024-03-17T14-50-44.567854327Z--35e6632f8c633d1cc299c88b6d6ec1646c57385b.json"
  chainId: 721