ktor:
  environment: "dev"
  deployment:
    port: 8080
  application:
    modules:
      # 配置数据库
      - moe._47saikyo.drm.backend.configuration.exposed.DatabaseConfigurationKt.configureDataSource
      # 配置Koin依赖注入
      - moe._47saikyo.drm.backend.configuration.koin.KoinKt.configureKoin
      # 配置鉴权模块
      - moe._47saikyo.drm.backend.configuration.security.SecurityKt.configureSecurity
      # 配置区块链接口
      - moe._47saikyo.drm.backend.configuration.BlockChainKt.configureBlockChain
      # 配置HTTP策略
      - moe._47saikyo.drm.backend.configuration.HTTPKt.configureHTTP
      # 配置IPFS接口
      - moe._47saikyo.drm.backend.configuration.IpfsKt.configureIpfs
      # 配置序列化插件
      - moe._47saikyo.drm.backend.configuration.SerializationKt.configureSerialization
      # 启用全部Controller路由
      - moe._47saikyo.drm.backend.ApplicationKt.enableAllControllers

global:
  exposed:
    datasource:
      driverClassName: "org.mariadb.jdbc.Driver"
      username: "root"
      password: "123456"
  JWT:
    subject: "Digital Right Manager Access License"
    issuer: "Digital Right Manager"
    audience: "Browser Application"
    secret: "secret"
  chain:
    manager: "0x13598c1e0e73d0793a29e35e8831aad41e40bfdc"
    address: "0x4db3443fc610477a5260c350254c9003b63e0673"
    password: "1234567890"
    chainId: 721
  #  gasPrice: 500000
  #  # 0xffffffff
  #  gasLimit: 4294967295

prod:
  exposed:
    datasource:
      jdbcUrl: "jdbc:mariadb://172.17.0.1:3306/drm-backend?characterEncoding=utf-8&serverTimezone=Asia/Shanghai"
  chain:
    socket: "http://172.17.0.1:8545"
    walletFile: "/root/drm-backend/KeyStore/bank-wallet.json"
  IPFS:
    address: "/ip4/172.17.0.1/tcp/5001"

dev:
  exposed:
    datasource:
      jdbcUrl: "jdbc:mariadb://127.0.0.1:3306/drm-backend?characterEncoding=utf-8&serverTimezone=Asia/Shanghai"
  chain:
    socket: "http://172.17.0.1:8545"
    walletFile: "/home/smile_slime_47/Projekt/Digital-Rights-Management/drm-backend/src/main/resources/KeyStore/UTC--2024-03-16T14-15-01.824378618Z--cb7f6d5c8f5c71c3f604f6fec874a97007dfe4fe.json"
  IPFS:
    address: "/ip4/127.0.0.1/tcp/5001"