version: '3'
services:
  ethereum_forward_nginx:
    image: nginx:latest
    container_name: ethereum_forward_nginx
    ports:
      - '8545:8545'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  ethereum_boot_node:
    image: drm-ethereum:1.0.4
    container_name: ethereum_boot_node
    volumes:
      - ./ethereum/boot:/root/drm-ethereum
    ports:
      - '30303:30303'
    networks:
      priv-ethereum-net:
    command:
      --datadir="/root/drm-ethereum"
      --nodekeyhex="aa2cd35ec09e9c85f28fa5655fb5fa5f07b7d4fd30eff152cdd5b345220637d5"
      --networkid=721
      --nodiscover
      --ipcdisable
      --netrestrict="172.21.0.0/16"
  ethereum_node_0:
    image: drm-ethereum:1.0.4
    container_name: ethereum_node_0
    volumes:
      - ./ethereum/node0:/root/drm-ethereum
    ports:
      - '8546:8545'
    depends_on:
        - ethereum_boot_node
    networks:
      priv-ethereum-net:
    command:
       --datadir="/root/drm-ethereum"
       --bootnodes="enode://d184b2ed048e114ab581175964eb19dff717f540dc203dabe807a1f46c9220b7d495e675184bfd665b96e17c121cc45ccd7b20d195842aff1fca9df6e8b66282@ethereum_boot_node:30303"
       --networkid=721
       --http
       --http.addr="0.0.0.0"
       --http.api="personal,eth,net"
       --http.corsdomain="*"
       --http.vhosts="*"
       --mine
       --miner.threads=2
       --miner.etherbase="0xcb7f6d5c8f5c71c3f604f6fec874a97007dfe4fe"
       --netrestrict="172.21.0.0/16"
  ethereum_node_1:
    image: drm-ethereum:1.0.4
    container_name: ethereum_node_1
    volumes:
      - ./ethereum/node1:/root/drm-ethereum
    ports:
      - '8547:8545'
    depends_on:
      - ethereum_boot_node
    networks:
      priv-ethereum-net:
    command:
      --datadir="/root/drm-ethereum"
      --bootnodes="enode://d184b2ed048e114ab581175964eb19dff717f540dc203dabe807a1f46c9220b7d495e675184bfd665b96e17c121cc45ccd7b20d195842aff1fca9df6e8b66282@ethereum_boot_node:30303"
      --networkid=721
      --http
      --http.addr="0.0.0.0"
      --http.api="personal,eth,net"
      --http.corsdomain="*"
      --http.vhosts="*"
      --mine
      --miner.threads=2
      --miner.etherbase="0xcb7f6d5c8f5c71c3f604f6fec874a97007dfe4fe"
      --netrestrict="172.21.0.0/16"
networks:
  priv-ethereum-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
